language: java
before_install:
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
    include:
        - env: JDK='Oracle JDK 10'
          install: . ./install-jdk.sh -F 10 -L BCL
script: mvn clean package
